version: "3"

services:
  react-app:
    image: react-app-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - flask-app

  flask-app:
    image: flask-app-1
    build:
      context: ./backend
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
