# Use the official Python image as the base image
FROM python:3.8-alpine

# Set the working directory in the container
WORKDIR /raghavaportfolio

# Copy the requirements file to the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire app to the container
COPY . .

# Expose the port that the Flask app will run on
EXPOSE 5000

ENV NAME backend

# Start the Flask app
CMD ["python", "app.py"]
